name: Android assemble

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run build processor task
        run: ./gradlew :processors:build
      - name: Run Android assemble task
        run: ./gradlew :demo:app:assembleDemoDebug

